### ISSUE TITLE
Trying to use the firmware hack python scripts

### ISSUE THREAD

**Issue by gadget78** [EliasKotlyar/Xiaomi-Dafang-Hacks#1487]
### Description
Trying to "unpack" a demo.bin firmware
(to repack with hack)

### What did you do to debug the issue
have tried using python 2, and python 3
python 2 has its version of click installed (pip install -U click), 
and pthon3 also has click installed
```
Collecting click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Installing collected packages: click
Successfully installed click-7.1.2
```

### Evidence
both/all python versions i have tried all comes back with the same error... 

Python2
```
linux@MainPC:~/.camera$ python2 ./unpacker.py demo.bin
Traceback (most recent call last):
  File "./unpacker.py", line 26, in <module>
    cli()
  File "/home/linux/.local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linux/.local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linux/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linux/.local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./unpacker.py", line 21, in cli
    f = open(filename, "wb")
IOError: [Errno 2] No such file or directory: 'flash/kernel.bin'
```

Python3
```
linux@MainPC:~/.camera$ python3 ./unpacker.py demo.bin
Traceback (most recent call last):
  File "./unpacker.py", line 26, in <module>
    cli()
  File "/home/linux/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linux/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linux/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linux/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./unpacker.py", line 21, in cli
    f = open(filename, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'flash/kernel.bin'
```

**Comment by gadget78** [comment]
after a an embarrassing amount of time spent debugging,  (trying different versions, under linux/windows etc)
found the problem, its because it didn't have a `/flash` folder for it to copy stuff to !
